// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAroppLoTezVipHFanqvXhIJtrOkAWqsU',
    appId: '1:987400774995:android:2085f95bd72993ed786da6',
    messagingSenderId: '987400774995',
    projectId: 'ah-chat-a7da9',
    storageBucket: 'ah-chat-a7da9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtvWlSGpGplS0ROyuHX37yPF7qtrbRJ8',
    appId: '1:987400774995:ios:44d9bf2b835c1c56786da6',
    messagingSenderId: '987400774995',
    projectId: 'ah-chat-a7da9',
    storageBucket: 'ah-chat-a7da9.appspot.com',
    androidClientId: '987400774995-8btspc89n9ut473c12o5eo7k63qo6cni.apps.googleusercontent.com',
    iosClientId: '987400774995-dgfvkserh6v46g88043f7p7icq180bve.apps.googleusercontent.com',
    iosBundleId: 'com.sanadapp.sanadApp',
  );

}